# Generated by Django 5.2.8 on 2025-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('AULA', 'Aula'), ('PROGRAMACAO', 'Programação'), ('CURSOS', 'Outros'), ('OUTROS', 'Outros'), ('TERRORPSI', 'Terror Psicológico')], max_length=20),
        ),
    ]
